apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kib-manual
  name: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-manual
  template:
    metadata:
      labels:
        app: kib-manual
    spec:
      containers:
      - image: kibana:8.18.0
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://es-service:9200"
        # Disable security for dev
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "none"
        - name: xpack.security.enabled
          value: "false"

        # livenessProbe:
        #   httpGet:
        #     port: http
        #     path: /status
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /status
        #     port: http
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
