apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  type: NodePort
  selector:
    app: logstash-logging
  ports:
  - protocol: TCP
    port: 5044
    name: logstash-beats
    targetPort: 5044
    nodePort: 31111 # or leave out to auto-assign
  - protocol: TCP
    port: 5050
    name: logstash-tcp
    targetPort: 5050
    nodePort: 31112 # or leave out to auto-assign